### ISSUE TITLE
Conflict with categories_as_tags plug-in

### ISSUE THREAD

**Issue by fengyedou** [ixti/redmine_tags#101]
Hi,
can you fix conflict with  categories_as_tags  plug-in? This plug-in is fromhttps://github.com/dkuk/categories_as_tags
When I installed redmine_tags there is such error, for I have a plug-in: categories_as_tags already.

D:\BitNami\redmine-2.3.2-0\apps\redmine\htdocs>bundle exec rake redmine:plugins:
migrate RAILS_ENV=production --trace
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://ruby
gems.org' if not.
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/watchr-0.7/lib/watchr.r
b:111: Use RbConfig instead of obsolete and deprecated Config.
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
Polyglot: found more than one candidate for D:/BitNami/redmine-2.3.2-0/apps/redm
ine/htdocs/config/environment.rb: D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs
/config/environment.rb, D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/config/en
vironment.rb.
rake aborted!
Expected D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/plugins/categories_as_ta
gs/app/helpers/filters_helper.rb to define FiltersHelper
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:503:in `load_missing_constant'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:192:in `block in const_missing'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:190:in `each'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:190:in `const_missing'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:514:in `load_missing_constant'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:192:in `block in const_missing'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:190:in `each'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:190:in `const_missing'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/plugins/redmine_tags/app/helpers/
tags_helper.rb:23:in `<module:TagsHelper>'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/plugins/redmine_tags/app/helpers/
tags_helper.rb:21:in `<top (required)>'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/polyglot-0.3.3/lib/poly
glot.rb:63:in `require'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/polyglot-0.3.3/lib/poly
glot.rb:63:in `require'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:251:in `block in require'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:236:in `load_dependency'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:251:in `require'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:359:in `require_or_load'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:313:in `depend_on'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/dependencies.rb:225:in `require_dependency'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/a
bstract_controller/helpers.rb:135:in `block in modules_for_helpers'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/a
bstract_controller/helpers.rb:131:in `map!'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/a
bstract_controller/helpers.rb:131:in `modules_for_helpers'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/a
ction_controller/metal/helpers.rb:92:in `modules_for_helpers'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/a
bstract_controller/helpers.rb:95:in `helper'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/plugins/redmine_tags/lib/redmine_
tags/patches/add_helpers_for_issue_tags_patch.rb:25:in `apply'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/plugins/redmine_tags/init.rb:50:i
n `block (2 levels) in <top (required)>'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/plugins/redmine_tags/init.rb:49:i
n `each'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/plugins/redmine_tags/init.rb:49:i
n `block in <top (required)>'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/callbacks.rb:506:in `_run__988203616__prepare__1034058791__call
backs'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/callbacks.rb:405:in `__run_callback'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.13/li
b/active_support/callbacks.rb:81:in `run_callbacks'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/a
ction_dispatch/middleware/reloader.rb:74:in `prepare!'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/a
ction_dispatch/middleware/reloader.rb:48:in `prepare!'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rai
ls/application/finisher.rb:47:in `block in <module:Finisher>'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rai
ls/initializable.rb:30:in `instance_exec'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rai
ls/initializable.rb:30:in `run'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rai
ls/initializable.rb:55:in `block in run_initializers'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rai
ls/initializable.rb:54:in `each'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rai
ls/initializable.rb:54:in `run_initializers'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rai
ls/application.rb:136:in `initialize!'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rai
ls/railtie/configurable.rb:30:in `method_missing'
D:/BitNami/redmine-2.3.2-0/apps/redmine/htdocs/config/environment.rb:14:in `<top
 (required)>'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/polyglot-0.3.3/lib/poly
glot.rb:63:in `require'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/polyglot-0.3.3/lib/poly
glot.rb:63:in `require'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rai
ls/application.rb:103:in `require_environment!'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rai
ls/application.rb:297:in `block (2 levels) in initialize_tasks'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:236:in `call'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:236:in `block in execute'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:231:in `each'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:231:in `execute'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:175:in `block in invoke_with_call_chain'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchroniz
e'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:168:in `invoke_with_call_chain'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:197:in `block in invoke_prerequisites'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:195:in `each'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:195:in `invoke_prerequisites'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:174:in `block in invoke_with_call_chain'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchroniz
e'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:168:in `invoke_with_call_chain'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ta
sk.rb:161:in `invoke'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ap
plication.rb:149:in `invoke_task'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ap
plication.rb:106:in `block (2 levels) in top_level'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ap
plication.rb:106:in `each'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ap
plication.rb:106:in `block in top_level'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ap
plication.rb:115:in `run_with_threads'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ap
plication.rb:100:in `top_level'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ap
plication.rb:78:in `block in run'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ap
plication.rb:165:in `standard_exception_handling'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/lib/rake/ap
plication.rb:75:in `run'
D:/BitNami/redmine-2.3.2-0/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.1/bin/rake:33
:in `<top (required)>'
D:/BitNami/redmine-2.3.2-0/ruby/bin/rake:23:in `load'
D:/BitNami/redmine-2.3.2-0/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by marius-balteanu** [comment]
Redmine version 2.* are no longer supported by this plugin. Please reopen this ticket if the issue reproduces on Redmine 3.* version and with the latest version of this plugin.
