### ISSUE TITLE
Multiple tags filtering behavior

### ISSUE THREAD

**Issue by rsvargas** [ixti/redmine_tags#103]
For every field that I can filter, I can set the operation to "equals" expand the select to a multiple select, select various values and hit apply.

Then it will show all issues that have ANY od the values I selected.

However when using the Tags field it will show only issues that have ALL the values.

I figured that this can be changed simply by adding a `:any => true` parameter to the `tagged_with` filter in lib/redmine_tags/patches/query_patch.rb:55).

Is this the intended behavior or it's really a defect?

**Comment by PowerKiKi** [comment]
I would say coherence would dictate to follow what is done for other fields and consider current behavior as a defect. But I am not quite convinced it would the best solution. Any arguments in favor of one way or another ?

**Comment by ixti** [comment]
It was desired behavior for me. :D So it was not a defect. I can see it's not perfectly fits all. So I have no objections against changing that.

**Comment by rsvargas** [comment]
I haven't seen this in any other fields, but maybe a checkbox named "any" or a new operation "contains all" ?

**Comment by marius-balteanu** [comment]
@rsvargas, this feature request is still available?

**Comment by rsvargas** [comment]
@marius-balteanu do you mean, can you do it? I believe so, I'm not the mantainer here. I really didn't do anything else than adding `:any => true`.

**Comment by marius-balteanu** [comment]
@rsvargas, sorry, I misunderstood the issue description. I tested now the scenario on the latest plugin version and I would also say that it's a bug.
