### ISSUE TITLE
Add ability to specify scope for tags

### ISSUE THREAD

**Issue by jprui** [ixti/redmine_tags#105]
Is it possible to specify the scope for tags so that instead of being visible across all projects, a tag would just be visible within a certain project and all its descendants?

When using redmine with multiple projects, some public and some private, it would be nice to keep the list of tags in separate lists

**Comment by marius-balteanu** [comment]
Hi @jprui,

In the current version from master branch the autocomplete for tags returns only the tags from that project. Can you test please and confirm that meets your expectations?

Thanks,
Marius

**Comment by jprui** [comment]
Marius,

Unfortunately, we are using an older version of redmine (2.2.1) and it is not real convenient to try this on the current version. So I can't offer real feedback based on using the new version.

From your description, only returning tags for the current project would be a big improvement over using tags across all projects. I was hoping for something like Search where you could specify the scope as being just the current project or current project and all sub-projects, or all projects for which I am a member, etc. But, now that I think about it, just doing the current project would be pretty good. 

Thanks.

**Comment by PowerKiKi** [comment]
I would be in favor to close this issue, since it is half-solved. What do you think @marius-balteanu, do you plan to implement something soon ?

**Comment by marius-balteanu** [comment]
It'll be to much work for us to make the plugin compatible with Redmine older versions (like 2.2.1) or to keep two branches (one for the older version and one for 3.* versions).

@jprui, you can try to implement this change https://github.com/ixti/redmine_tags/commit/538fa70de6ca61ca9d750388b3ef10432980f20c in our version. That was the change made by us to return only the tags from that project.
