### ISSUE TITLE
Can not find tags in the general search of redmine?

### ISSUE THREAD

**Issue by liomoura** [ixti/redmine_tags#108]
Can not find tags in the general search of redmine?

![image](https://cloud.githubusercontent.com/assets/10420467/7836883/380d756e-045a-11e5-8564-bfb882eff9bb.png)

**Comment by marius-balteanu** [comment]
@liomoura, this feature request is still available?

**Comment by PowerKiKi** [comment]
Closing this for lack of feedback, interest and manpower.
