### ISSUE TITLE
Allow to prefill tags via http url parameter

### ISSUE THREAD

**Issue by jcppkkk** [ixti/redmine_tags#109]
Refer to http://www.redmine.org/issues/9076

I want to use GET parameter to set tags on new issue page, but it seems redmine_tags does not support this behavior:

http://www.redmine.org/redmine/proweb/issues/new?issue[tag_list]=my_tag

**Comment by marius-balteanu** [comment]
@jcppkkk, this feature request is still available?

**Comment by jcppkkk** [comment]
I think it's up to you now since i don't need this anymore.

I ran into this issue when i tried to setup a report page for redmine novices. most fields can be auto filled with values set in URL, except redmine_tags's tag field.

**Comment by marius-balteanu** [comment]
@jcppkkk, thanks for info, I'll close the ticket for the moment.

**Comment by thybzi** [comment]
I still need this feature, as I need to create tickets by opening `issues/new` page with subject and tags prefilled
