### ISSUE TITLE
Multiple tags merged into one on issue edit 

### ISSUE THREAD

**Issue by glatapoui** [ixti/redmine_tags#110]
When you edit an Issue containing multiple tags, they are all merged into a big one.
This happens with the integration of https://github.com/EtherealLich/redmine_tags and https://github.com/EtherealLich/acts-as-taggable-on/blob/patch-1/lib/acts_as_taggable_on/acts_as_taggable_on/core.rb.

Is this issue already known ?

**Comment by PowerKiKi** [comment]
This is the wrong repository to report an issue about forked project. Closing
