### ISSUE TITLE
Issues clean-up

### ISSUE THREAD

**Issue by marius-balteanu** [ixti/redmine_tags#112]
Hi @ixti, @PowerKiKi, @sdwolf,

There are 31 opened issues on this project and 25 are older that 1 year. My proposal is to close and comment them (issues > 1 year) with a general message "Please try the latest version and reopen if the issue is still available".

Waiting for you opinion/proposals.

Thanks,
Marius

**Comment by PowerKiKi** [comment]
That sound very reasonable to me.

Also I was going to suggest to release a 3.1.0 version (via git tag). That way it would higher than marius-balteanu/redmine_tags (3.0.3) and this project (2.1.0)

**Comment by ixti** [comment]
:+1: Absolutely agree that's it's safe to close old issues.

**Comment by marius-balteanu** [comment]
Great, I'll post the message and close the issues these days.
