### ISSUE TITLE
Issue Not Open

### ISSUE THREAD

**Issue by adrianobr** [ixti/redmine_tags#118]
Issue not open after the instalation this plugin

**Comment by sdwolf** [comment]
Can you please give more details about your problem?
Any of the follwoing will help: ruby version, redmine version, a list o installed plugins with their versions, exact steps you took to get to this problem, any other details worth mentioning...

**Comment by snowball341** [comment]
Same problem. 'Internal error'

Environment:
>  Redmine version                3.2.0.stable
>  Ruby version                   2.2.3-p173 (2015-08-18) [i686-linux]
>  Rails version                  4.2.5
>  Environment                    production
>  Database adapter               Mysql2
SCM:
>  Subversion                     1.6.11
>  Mercurial                      1.4
>  Git                            1.7.1
>  Filesystem                     
Redmine plugins:
>  a_common_libs                  1.1.9
>  redmine_checklists             3.1.3
>  redmine_issue_tabs             1.1.1
>  redmine_issues_tree            0.0.5
>  redmine_tags                   3.1.0
>  redmine_workflow_enhancements  0.5.0

**Comment by marius-balteanu** [comment]
Tested on 3.2.0 and works fine.
Updated Readme file  to include the entire migration command in order to avoid issues like this.

**Comment by adrianobr** [comment]
Hi, 

I performed the test this morning and still the problem by opening the task

Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.6.4
  Filesystem                     
Redmine plugins:
  accept                         0.0.1
  clipboard_image_paste          1.10
  my_projects                    1.4
  progressive_projects_list      2.0.1
  redmine__select2               1.0.5
  redmine_backlogs               v1.0.6
  redmine_checklists             3.1.3
  redmine_emojibutton            0.4.1
  redmine_gamification_plugin    0.0.4
  redmine_graphs                 0.1.0
  redmine_issue_number_favicon   0.0.1
  redmine_jstoolbar_ext          0.2.1
  redmine_jstoolbar_ext_coderay  0.2.0
  redmine_lightbox2              0.2.4
  redmine_login_audit            0.2.2
  redmine_monitoring_controlling 0.1.1
  redmine_move_comments          0.0.2
  redmine_mylyn_connector        2.8.2.stable
  redmine_people                 1.1.1
  redmine_pushover               1.0.1
  redmine_revision_branches      0.3.0
  redmine_spent_time             3.1.2
  redmine_sticky_messages        1.0.1
  redmine_timesheet_plugin       0.7.0
  redmine_workflow_enhancements  0.5.0
  redmine_zenedit                0.0.2
  redrisk                        1.0.1
  release_logs                   1.0.0
  sidebar_hide                   0.0.7
  simple_author_change           0.1.1
  timelog_timer                  2.0.0
