### ISSUE TITLE
Suggestions does not recognize words

### ISSUE THREAD

**Issue by lesonkorenac** [ixti/redmine_tags#137]
Hello,

Suggestion feature seems to be broken, since often does not suggest nothing and sometimes it suggest only some tags.

For example I have defined tags: 

Server
Client
C++
Java
JavaScript

When I start typing Ja, nothing is suggested,
when I start typing S, JavaScript is suggested,
When I start typing c, Client is suggested

Lesoň

**Comment by L0rD59** [comment]
Hi,

For information, i haven't this problem with `plugins/redmine_tag : master#a348cd4` and `redmine: 3.3-stable`

**Comment by lesonkorenac** [comment]
Still does not work. This issue is duplicated by issue #141 (which pinpoints where the problem is - anotherJay's fix worked for me).

My redmine info:

Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Cvs                            1.12.13
  Git                            2.6.1
  Filesystem                     
Redmine plugins:
  redmine_all_issues             0.0.1
  redmine_didyoumean             1.2.0
  redmine_tags                   3.1.1
  time_logger                    0.5.3

**Comment by marius-balteanu** [comment]
Suggestion feature works and issue #141 was fixed in the last plugin version.

Please reopen if you still have problems.
