### ISSUE TITLE
AutoComplete can't find tags using capital letters

### ISSUE THREAD

**Issue by anotherJay** [ixti/redmine_tags#141]
If we have a tag with a capital letter in it, we can't find it using the auto-complete on the issue edit page.

Example: if you have a tag "Bug", if you type "b" it won't be found, if you type "B" it won't be found, you can only find it if you type "u" or "g".

It appears that this is because the tag.name column is defined with "COLLATE utf8_bin" (https://github.com/ixti/redmine_tags/commit/7317014d3b00d073c46ec8d4df9546fc8e290b30#diff-689b528be1fc2fcfc616b6380d3968cbR51), which makes the LIKE comparison case-sensitive, but the query parameter is converted to lower case, so it can never find capital letters.

Testing on Redmine 3.2.2 and latest version of the plugin.

**Comment by markedagain** [comment]
+1

**Comment by AstraSerg** [comment]
No luck with postgresql

**Comment by markedagain** [comment]
@AstraSerg the query is for only mysql since its explicitly checks for db type before running the "migration" Also my fix presumes you dont care for case sensitivity , if this is also the case for you and you dont want to hack away at code, i believe googling postgresql case senstive columns will yield you a good solution

**Comment by L0rD59** [comment]
Hi,

For information, i haven't this problem with `plugins/redmine_tag : master#a348cd4` and `redmine: 3.3-stable`

**Comment by anotherJay** [comment]
Another fix is to apply the COLLATE statement to just the query:

https://github.com/anotherJay/redmine_tags/commit/4883c1ece0fc1da94eb7b92714a2124ff37c2b15

**Comment by anotherJay** [comment]
I'm not really a redmine plugin developer so I'm not sure if that is worth submitting as a pull request since I don't know how to add tests, etc.

**Comment by marius-balteanu** [comment]
Fixed in 3.2.0 using another solution (dfaaf1d74e430c538e01cb17855ae0c54c14cb32)
