### ISSUE TITLE
Please stop updating the 1 db patch file and create new ones for new patches 

### ISSUE THREAD

**Issue by markedagain** [ixti/redmine_tags#150]
Took us some time to figure this one out. you are not creating new patch files for db migrations. We have had the repo for a very long time, and act_as_taggable has had alot of changes happen to the tables structure. but you only update the main patch file, and this patch file wont rerun for us since we already have it applied to our db schema. so we were never getting the new changes. the only work around was to manually update all the tables based on your and gems patch files and running the queries directly.

**Comment by sdwolf** [comment]
We intended to make that one file backwards compatible with the previous ones and just remove the intermediary columns, maybe we got carried away, can you please highlight which changes you were not getting?

**Comment by markedagain** [comment]
i had to run the last 4 patch files manually(reverse engineered it into a mysql queri) from act_as_tagable gem. im unsure how i was so far behind in the versions on your plugin. Its possible i installed your plugin over 1 year ago. the tag_counts was missing taggins.contexts was missing and something else i cant remember.  Sorry i did not keep a more logged detail of all the errors for the missing columns

**Comment by sdwolf** [comment]
Thank you for the insight, the acts_as_taggable_on dependency was a nightmare when upgrading for redmine 3.x. I'm afraid the damage was my fault. 
I'l keep in mind when acts_as_taggable_on has new migrations to add them in a new file and check if they were not already present in the DB.
