### ISSUE TITLE
Incompatible with 3.3.2

### ISSUE THREAD

**Issue by sdwolf** [ixti/redmine_tags#160]
I took a quick look and it seems tags are not saved when submitting in 3.3.2.

Will investigate further.

**Comment by sdwolf** [comment]
Weirdly, this issue is no longer reproducible... I will keep an eye out for it happening again.
It seemed to happen the first time when creating an issue after a fresh install with a new database and default settings. But it disappeared once I got my debugger set up :neutral_face:

**Comment by marius-balteanu** [comment]
I'll try to test this week with 3.3.2

**Comment by ilpssun** [comment]
I just installed yesterday on 3.3.2 and it seems to be working fine.  I only tested tagging tickets, though.

**Comment by PowerKiKi** [comment]
If this can't be reproduced and others have no issues, shouldn't it be closed ? or is there still some possibilities of incompatibilities ?

**Comment by sdwolf** [comment]
I was waiting for @marius-balteanu to confirm, but since there was no problem untill now, i'l take another look this evening and close it.
