### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by gusztavj** [ixti/redmine_tags#164]
Hey Guys, I'm pretty sure I'm total dumb, but I simply cannot figure out how to use this plugin. I was expecting a custom field type called Tag to appear for, at least, the Issues object type. But I can't find anything like that. So what's the next step in getting happy with the plugin, once it's been enabled? :)

Cheers,
Gus

**Comment by PowerKiKi** [comment]
Did you restart Redmine ? Is it listed under /admin/plugins ?

**Comment by gusztavj** [comment]
Yep it was. Finally the problem solved by itself, it took some time for the tag field to automatically appear on pages of supported object types.
