### ISSUE TITLE
Redmine 3.4.X compatibility (error 500)

### ISSUE THREAD

**Issue by kalumkalac** [ixti/redmine_tags#182]
Hello, the plugin redmine_tags is not compatible with Redmine 3.4. It's fine on Redmine 3.3 though.

See this issue posted on Redmine tracker: http://www.redmine.org/issues/26637

I did check by myself, disabling this plugin makes the error disappear.

**Comment by sdwolf** [comment]
I've updated travis for redmine 3.4 and tests still pass, also tested it locally and can't reproduce. We also have redmie 3.4.2 and latest tags in production and no issues found so far.

To better help you with your issue, please provide a stacktrace, as complete as you can, together with your exact redmine and ruby versions and a list of all your installed plugins.

**Comment by kalumkalac** [comment]
You are right, after disabling all plugins, I upgraded to 3.4.2 and it does work. I think it's related to the fact I was upgrading all my plugins and redmine version alltogether from 2.6.6 version... I'm not sure. We can close that.
