### ISSUE TITLE
Ability to create query by tags with AND logic

### ISSUE THREAD

**Issue by oivanenko** [ixti/redmine_tags#196]
Hi!

It would be great if I can create query with AND logic for several tags. For example if I have issues with those tags

Issue1 - tag1, tag2, tag3
Issue2 - tag3, tag4, tag 5

and I'll create query by Tags with multiple tags selected (e. g. tag2 + tag3) it will show both of issues (OR logic), instead Issue1 as I want to (AND logic).

**Comment by marius-balteanu** [comment]
Thanks for the feature request.  Unfortunately, we need to wait for Redmine to support such functionality in the query model. Now I'll close this ticket because I'm not going to implement something custom. Sorry for the bad news.
