### ISSUE TITLE
crash on Issues page

### ISSUE THREAD

**Issue by eashman** [ixti/redmine_tags#20]
Running Redmine 2.2.2:

1. If you don't have any settings in the settings db (ie. you just installed the plugin for the first time), you can use the site and issues pages but you don't see the tags, obviously.
2. When you config the plugin, it saves the row to the DB but then **doesn't show the values in the config screen** - they are set back to defaults.  I think it's not able to actually parse the settings or something post INSERT.
3. if you config the plugin (unsuccessfully as far as the UI is concerned) and it creates the row in the settings DB table and you go to view an issue- you get the error below in logs.
4. if you manually remove the settings DB row, all is well but no tags.

ActionView::Template::Error (undefined method `to_sym' for nil:NilClass):
    1: <% unless sidebar_tags.empty? -%>
    2:   <%= stylesheet_link_tag 'jquery.tagit.css', :plugin => 'redmine_tags' %>
    3:   <%= stylesheet_link_tag 'redmine_tags', :plugin => 'redmine_tags' %>
    4:   <h3><%= l(:tags) %></h3>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_sidebar.html.erb:14:in `_app_views_issues__sidebar_html_erb__602694580907020990_70120344284040'
  app/views/issues/index.html.erb:93:in `block in _app_views_issues_index_html_erb__4074005188923787004_62866580'
  app/helpers/application_helper.rb:1145:in `content_for'
  app/views/issues/index.html.erb:92:in `_app_views_issues_index_html_erb__4074005188923787004_62866580'
  app/controllers/issues_controller.rb:83:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:82:in `index'

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
