### ISSUE TITLE
Move this plugin to the core

### ISSUE THREAD

**Issue by marius-balteanu** [ixti/redmine_tags#203]
FYI, I've started work on moving this plugin to the Redmine core (please see http://www.redmine.org/issues/1448#change-86793).

I'll add support for Redmine 4.0.0 right after is released and after that, hopefully, I'll work only on patches for the core.

Please let me know if you consider that I should this note to the Readme.

**Comment by PowerKiKi** [comment]
Thanks for doing this. I hope it will get merged in core

**Comment by ixti** [comment]
That is amazing! Sure, I think it worth to note that this plugin is EOL soon and that further development will be happening in redmine core.

Huge thanks for all the work and efforts you have put into redmine-tags over the last years!

**Comment by marius-balteanu** [comment]
I've released the new version of the plugin (4.0.0) that supports only Redmine 4.0.0. The changes to support older Redmine are too big and it doesn't worth it considering the plugin EOL.

@PowerKiKi, @ixti, if you can update the version on http://www.redmine.org/plugins/redmine_tags it will be great.

**Comment by jcormier** [comment]
Did this ever get merged into redmine?
