### ISSUE TITLE
Rights to add back integration with Travis

### ISSUE THREAD

**Issue by marius-balteanu** [ixti/redmine_tags#205]
I think that @sdwolfz removed his GitHub account and because of that, the integration with Travis doesn't work anymore. 

Can you give me rights  to add back the integration? Currently, I don't see the Settings option for this repository.

Thanks.

**Comment by sdwolfz** [comment]
I don't remember touching anything related to TravisCI... I can still access the project and modify it's settings, re-trigger old builds, but on the `Current` tab I have:
```
This is not an active repository
You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself.
```
Maybe something is wrong with TravisCI itself `¯\_(ツ)_/¯`.

**Comment by marius-balteanu** [comment]
:( thanks for the checks, @sdwolfz. Maybe we should try to delete/add again the integration?

**Comment by ixti** [comment]
That was something wrong with TravisCI as I never been changing anything there. But when I opened redmine_tags on TravisCI just now it showed me the same "inactive" message with proposal to activate it.

**Comment by ixti** [comment]
Hope it's good now. Please let me know if I can assist/help somehow.

**Comment by marius-balteanu** [comment]
It's all good now, is building: https://travis-ci.org/ixti/redmine_tags/builds/426841929

**Comment by marius-balteanu** [comment]
@sdwolfz, do you have any idea why Travis does not found anymore the Gemfile?

**Comment by ixti** [comment]
`$REDMINE_PATH` is somehow empty, thus it tries to use `/Gemfile`...
