### ISSUE TITLE
redmine 5.x support

### ISSUE THREAD

**Issue by laf0rge** [ixti/redmine_tags#238]
Now that redmine upstream has released 5.x 7 months ago, it would be nice if this pluging could also support the latest stable release.

I'm not a ruby developer, so I cannot contribute code.  But let me know if it is possible to support you financially.

**Comment by PowerKiKi** [comment]
See if you can still help with https://github.com/ixti/redmine_tags/pull/233, even without coding. Or alternatively migrate to https://github.com/AlphaNodes/additional_tags

**Comment by ixti** [comment]
@PowerKiKi should we archive this project?

**Comment by PowerKiKi** [comment]
@ixti, yes it should absolutely be archived, thank you.
