### ISSUE TITLE
Refinements for tag colours

### ISSUE THREAD

**Issue by hdgarrood** [ixti/redmine_tags#25]
I do really like the idea of colouring tags -- it makes it much easier to see and recognise them. But, I think they could be made even better:

* some tags have a light colour, which makes it difficult to see the white text (eg: http://snag.gy/5AMqJ.jpg)
* some colours are just ugly
* some colours are a bit garish, and can sort of 'take over' the whole page

I don't really have too much of an idea of how to fix these issues. Perhaps changing the algorithm which chooses the colour so that colours are only taken from a pre-determined set or range?

I'll think more about this later.

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
