### ISSUE TITLE
'Merge' tags / tag synonyms?

### ISSUE THREAD

**Issue by hdgarrood** [ixti/redmine_tags#26]
If you end up with two tags which are essentially the same (eg 'tsql', 't-sql' -- see http://meta.stackoverflow.com/questions/2779/could-the-tagging-system-be-enhanced-to-support-tag-synonyms), you probably will want to change all the 't-sql' tags to 'tsql' tags, and ensure that 't-sql' tags automatically become 'tsql' tags in the future. This issue is for [an] extra feature[s] to facilitate this. Also I'm not really sure if this is a good idea yet.

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
