### ISSUE TITLE
Display amount of issues wrong query

### ISSUE THREAD

**Issue by delfo** [ixti/redmine_tags#36]
when 'Display amount of issues' is activated you may see the number of issues tagged with a specific tags in ALL the platform, but when clicking on it you are only redirected to a query listing the issues with selected tags in actual project... this sounds confusing
i would propose to count and display all the issues in actual project and subproject may with the chance to filter out the subproject through the usual issues filtering (filter and options)

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
