### ISSUE TITLE
add tags to projects

### ISSUE THREAD

**Issue by delfo** [ixti/redmine_tags#40]
as the core redmine is not allowing project portfolio management at my company we bought easyredmine plugin which allows to see all the projects in a issues list manner so that you can filter and set showing options

it would be nice so to be able to add tags also at project level in order to be able to easily categorize the projects on the platform

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.

**Comment by mxmader** [comment]
@delfo suggest you re-open this as "projects" are not listed as a supported model of this plugin.
