### ISSUE TITLE
activation on project basis

### ISSUE THREAD

**Issue by delfo** [ixti/redmine_tags#41]
would be nice to be able to activate/deactivate tagging on a project basis

statuses could be: 

disable: cannot read/cannot add tags
readonly: can read / cannot add
active: can read / can add
reset: erase all the tags in the project (to be confirmed by user)

when switching to disable previously created tags wouldn't be erased

properties should be inherited by parent projects

E.g: P1->P2

if tags in P2 are disabled, showing tags in P1 will not icnldue the tags in P2 issues if any

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
