### ISSUE TITLE
Overwriting tags when editing issues in bulk

### ISSUE THREAD

**Issue by hdgarrood** [ixti/redmine_tags#57]
When bulk editing a group of issues, if the issues have no tags in common, the tags list appears empty. If you put a tag in on the bulk edit page, instead of appending (which I think is what most people would expect), it replaces all those issues' tag lists. It's very easy to accidentally remove tags this way.

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
