### ISSUE TITLE
Only open tags counter / total count

### ISSUE THREAD

**Issue by smiodus** [ixti/redmine_tags#58]
I have checked two options "Display amount of issues" and "Display open issues only" with List display, counter on the right side shows up total amount of tagged issues but when I click on tag I see only opened. I think if I check "Display open issues only" that counter should show only opened tags value - I'm right?

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
