### ISSUE TITLE
Rename/Remove tags

### ISSUE THREAD

**Issue by jlhg** [ixti/redmine_tags#83]
It would be very flexible if a tag can be renamed or removed.
Also, would it be possible that two or more issues's tags are changed in bulk?
Thank you!

**Comment by cebas** [comment]
I would like to have this too

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
