### ISSUE TITLE
Cyrillic «Б» is not supported in tag names

### ISSUE THREAD

**Issue by peremenov** [ixti/redmine_tags#87]
Cyrillic «Б» is not supported in tag names: you cannot type a tag which includes a capital «Б» or a small «б» since plugin considers it to be a Latin comma.

Невозможно напечатать букву «Б» в имени метки.

**Comment by peremenov** [comment]
Probably this is a solution https://github.com/aehlke/tag-it/issues/324

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.

**Comment by ixti** [comment]
Well, this one is actually still exist. As it's a bug in tag-it that we use.

**Comment by ixti** [comment]
These are issue tickets related to this bug in tag-it:

- aehlke/tag-it#22
- aehlke/tag-it#140
- aehlke/tag-it#222
- aehlke/tag-it#251
- aehlke/tag-it#262
- aehlke/tag-it#324

Issue was reported on tag-it **4 years ago** and still not fixed.
I think we should probably switch to other module, e.g. the one that @PowerKiKi proposed: Select2.

**Comment by marius-balteanu** [comment]
Ok, I'm reopening the issue.

**Comment by PowerKiKi** [comment]
Since my last comment on this issue Select2 had a major version released (with lots of cleanup). That may make it an even better candidate. But we should be sure that it still works with latest version before implementing it...

**Comment by marius-balteanu** [comment]
Ok, we'll try in the next days to move from tagit to select2.

**Comment by marius-balteanu** [comment]
I made some tests yesterday and I don't think that we can move now easily from tag-it to select2 v4 (latest version) because of the incompatibility with other plugins that we use in our company ([A Common Libs](http://www.redmine.org/plugins/a_common_libs) that uses Select 2 version 3.4.1 and [Restrict Tracker](http://www.redmine.org/plugins/redmine_restrict_tracker) that depends on A Common Libs).

We can try to move to Select 3.4.1 or to wait for A Common Libs to adds Select2 v4.

**Comment by ixti** [comment]
Select2 v 3.4.1 will work perfectly fine (because it does not adds tag upon special chars - it waits for user to hit enter, or unfocus of input element).

**Comment by ixti** [comment]
Seems like this was fixed as of https://github.com/ixti/redmine_tags/pull/140
