### ISSUE TITLE
Support forum module

### ISSUE THREAD

**Issue by phaethon** [ixti/redmine_tags#92]
If forum module is used, then tagging with the same tags as used for issues would help. It seems enough to be able to add tag just for the topic and search forum entries by tags.

**Comment by cheoAlejo** [comment]
Good idea !

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
