### ISSUE TITLE
Incorrect render tags on Issue list

### ISSUE THREAD

**Issue by darioo** [ixti/redmine_tags#93]
I am using RM 2.5.1. Instead of correct Links and text of Tags I get raw html with html entitles:

<span class="tag-label-color" style="background-color: #ae0e4b"><a href="/projects/testy/issues?fields%5B%5D=tags&amp;operators%5Btags%5D=%3D&amp;set_filter=1&amp;values%5Btags%5D%5B%5D=bug">bug</a></span>, <span class="tag-label-color" style="background-color: #bec670"><a href="/projects/testy/issues?fields%5B%5D=tags&amp;operators%5Btags%5D=%3D&amp;set_filter=1&amp;values%5Btags%5D%5B%5D=story">story</a></span>, <span class="tag-label-color" style="background-color: #d975a4"><a href="/projects/testy/issues?fields%5B%5D=tags&amp;operators%5Btags%5D=%3D&amp;set_filter=1&amp;values%5Btags%5D%5B%5D=co%C5%9B+tam">coś tam</a></span>

I found that when I change line 45 at  /lib/redmine_tags/patches/queries_helper_patch.rb to  

column.value(issue).collect{ |t| URI.decode_www_form_component(render_tag_link(t)) }.join(', ').html_safe 

it looks ok (clickable links) but doesn't work - not shown issues with selected TAG.

Maybe some one can help

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
