### ISSUE TITLE
tags erased on change status issue

### ISSUE THREAD

**Issue by maiconzucco** [ixti/redmine_tags#94]
hi,

when I change the Status of the Issue, the tags inserted on interaction are deleted.
It's a bug?

Thanks.

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.

**Comment by peremenov** [comment]
It will be great to fix this! Does this bug fixed?

**Comment by marius-balteanu** [comment]
No, is not fixed.

**Comment by L0rD59** [comment]
Hi,

For information, i haven't this problem with `plugins/redmine_tag : master#a348cd4` and `redmine: 3.3-stable`

**Comment by marius-balteanu** [comment]
Fixed on PR #163.
