### ISSUE TITLE
Inheriting list of tags from sub projects to parent project

### ISSUE THREAD

**Issue by kfranckiewicz** [ixti/redmine_tags#96]
Hello,

Redmine version: 2.3.4.stable
Redmine tags version: 2.1.0

During work with this plugin I saw that list of tags (in side bar) in my sub projects is not inherited to parent project. I think that should be possible, similar as inherit versions in projects. Please on feedback.

Thanks,
Kamil F.

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
