### ISSUE TITLE
Error on rake redmine:plugins:migrate

### ISSUE THREAD

**Issue by rafaelmr2** [ixti/redmine_tags#98]
Erro no Redmine 2.5.1 (Debian Wheezy):

\# RAILS_ENV=production rake redmine:plugins:migrate

  (in /usr/share/redmine)
  rake aborted!
NameError: uninitialized constant RedmineActsAsTaggableOn
/var/lib/gems/1.9.1/gems/redmine_acts_as_taggable_on-1.0.0/lib/redmine_acts_as_taggable_on/migration.rb:3:in `<top (required)>'
/var/lib/gems/1.9.1/gems/redmine_acts_as_taggable_on-1.0.0/lib/redmine_acts_as_taggable_on/initialize.rb:3:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
